<template>
	<view class="profile-list">
		<view class="condition">
			<car-filter-button :filters="filters" width="20%" @click="filterAction"></car-filter-button>
			<view v-for="(item,index) in filters" :key="index">
				<u-action-sheet
					v-if="item.selects.length > 0"
					cancelText="取消" 
					:actions="item.selects"
					 @select="selectFilter" 
					 @close="item.show = false" 
					 :title="item.title"
					 :show="item.show"
				></u-action-sheet>
			</view>
			<u-datetime-picker
				:show="dateShow"
				v-model="date"
				:minDate="1587524800000"
				:maxDate="1786778555000"
				mode="date"
				@confirm="dateConfirm"
			></u-datetime-picker>
		</view>
		<view class="content">
			<uni-list :border="false">
				 <uni-list-item 
					:border="false"
					:thumb="item.logo"
					thumbSize="lg"
					v-for="(item,index) in list"
					:note="item.create_time"
					:key="index"
					:title="item.plate" 
					:showArrow="true"
					:rightText="item.username"
				>
				</uni-list-item>
			</uni-list>
			<u-loadmore :status="status"/>
		</view>
	</view>
</template>

<script>
	export default{
		onReachBottom() {
			if(this.page >= 3) return ;
			this.status = 'loading';
			this.page = ++ this.page;
			setTimeout(() => {
				for (let i=0;i<15;i++) {
					this.list.push({
						id:1,
						plate:'粤Y458645',
						username:'李四',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					})
				}
			}, 2000)
		},
		methods:{
			filterAction(e){
				e.show = true
				switch(e.actionName){
					case 'date':
						this.dateShow = true;
				}
			},
			dateConfirm(e){
				this.dateShow = false
				console.log(e)
			},
			selectFilter(e){
				console.log(e)
			}
		},
		data(){
			return{
				date:Number(new Date()),
				dateShow:true,
				status: 'loadmore',
				page: 0,
				filters:[
					{
						title:'类型',
						actionName:'type',
						show:false,
						selects:[
							{
								name:'手机',
							},
							{
								name:'vin码',
							},
							{
								name:'驾驶证',
							}
						]
					},
					{
						title:'月份',
						actionName:'date',
						show:false,
						selects:[]
					},
					{
						title:'操作人',
						actionName:'operator',
						show:false,
						selects:[
							{
								name:'张三',
							},
							{
								name:'李四',
							},
							{
								name:'王五',
							}
						]
					}
				],
				list:[
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					},
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					},
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					},
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					},
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					},
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					},
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					},
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					},
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					},
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					},
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					},
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					},
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					},
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					},
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					},
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					},
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					},
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					},
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					},
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					},
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					},
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					},
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					},
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					},
					{
						id:1,
						plate:'粤Y458645',
						username:'张三',
						create_time:'2022-11-15',
						logo:'https://juhe.oss-cn-hangzhou.aliyuncs.com/api_image/538/brand/2.png'
					}
				]
			}
		}
	}
</script>

<style lang="scss" scoped>
	.content{
		padding-top: 160rpx;
	}
</style>
